console.log('it is linked');
const canvas = (document).getElementById("my-canvas");
const ctx = canvas.getContext("2d");


// The board is generated by using two for loops that are less than 8 since the board is
// 8x8. The logic within the loops compares the location of x and y. If you mod x and y 
// by 2 and they equal to each other it will paint a 100x100 square black. If they are 
// not equal it will paint a 100x100 square red. This each loop runs 7 times painting each
// square as it goes.


const checkerBoard = {
	color1: 'black',
	color2: 'red',
	color() {
		for(let i = 0; i < 8; i++){
			for(let j = 0; j < 8; j++){
				if(i % 2 == j % 2){
					ctx.fillStyle = this.color1;
					ctx.fillRect(100 * i, 100 * j, 100, 100);
				} else {
					ctx.fillStyle = this.color2;
					ctx.fillRect(100 * i, 100 * j, 100, 100);
				}
			}
		}
	
	}
}

checkerBoard.color()

const makeBoard = () => {
	for(let i = 0; i <= canvas.width; i+= 100){
		ctx.beginPath();
		ctx.moveTo(i, 0);
		ctx.lineTo(i, canvas.width);
		ctx.stroke()
		ctx.closePath()
		ctx.beginPath();
		ctx.moveTo(0, i);
		ctx.lineTo(canvas.width, i);
		ctx.stroke()
		ctx.closePath();
	}
	
}
makeBoard()

// This event listener will find specific keydown presses within the document

$(document).on('keydown', (e) => {
	console.log(e);

	//g

	//y

	//r

	//w

	//b
})


